# Generated by Django 6.0.7 on 2026-08-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('yolo_class_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('calories_per_100g', models.FloatField(help_text='kcal per 100g')),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('is_healthy_flag', models.BooleanField(default=True)),
                ('healthier_alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nutrition.foodnutrition')),
            ],
            options={
                'verbose_name': 'Food Nutrition Record',
                'ordering': ['name'],
            },
        ),
    ]
